#!/bin/bash
# Pizza Craft Render Deployment Script
# This script creates 3 services on Render for the PizzaCraft application

echo "🍕 PizzaCraft Render Deployment"
echo "================================"
echo ""
echo "This script will deploy 3 services to Render:"
echo "1. Backend API (port 3001)"
echo "2. Frontend Website (port 5173)"
echo "3. Admin Dashboard (port 5001)"
echo ""
echo "Prerequisites:"
echo "- Render account (connected to GitHub)"
echo "- Pizza Craft repository accessible"
echo ""
echo "Steps to deploy:"
echo ""
echo "1. LOG IN to Render:"
echo "   Go to: https://dashboard.render.com"
echo "   Click 'GitHub' and authorize"
echo ""
echo "2. DEPLOY BACKEND API:"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Select 'pizza_craft' repository"
echo "   - Name: pizza-craft-api"
echo "   - Root Directory: project/server"
echo "   - Runtime: Node"
echo "   - Build: npm install"
echo "   - Start: npm start"
echo "   - Environment Variables:"
echo "     PORT=3001"
echo "     NODE_ENV=production"
echo "     MONGODB_URI=mongodb+srv://venkatasaigunda82_db_user:Lakshmisai%40321@cluster0.tlknxch.mongodb.net/?appName=Cluster0"
echo "     JWT_SECRET=pizza-craft-jwt-prod-2025"
echo "     RAZORPAY_KEY_ID=rzp_test_ODQ3lf6JSSFi9z"
echo "     RAZORPAY_KEY_SECRET=EI21xvagP5DUVcGEl1xtS8AK"
echo "   - Click 'Create Web Service'"
echo "   - Wait 5 mins, copy the URL (pizza-craft-api.onrender.com)"
echo ""
echo "3. DEPLOY FRONTEND:"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Select 'pizza_craft' repository"
echo "   - Name: pizza-craft-web"
echo "   - Root Directory: project"
echo "   - Runtime: Node"
echo "   - Build: npm install && npm run build"
echo "   - Start: npm run preview"
echo "   - Environment Variables:"
echo "     VITE_API_URL=https://pizza-craft-api.onrender.com"
echo "     NODE_ENV=production"
echo "   - Click 'Create Web Service'"
echo "   - Wait 5 mins, copy the URL"
echo ""
echo "4. DEPLOY ADMIN DASHBOARD:"
echo "   - Click 'New +' → 'Web Service'"
echo "   - Select 'pizza_craft' repository"
echo "   - Name: pizza-craft-admin"
echo "   - Root Directory: admin-dashboard"
echo "   - Runtime: Node"
echo "   - Build: npm install && npm run build"
echo "   - Start: npm run preview"
echo "   - Environment Variables:"
echo "     VITE_BACKEND_URL=https://pizza-craft-api.onrender.com"
echo "     NODE_ENV=production"
echo "   - Click 'Create Web Service'"
echo "   - Wait 5 mins, copy the URL"
echo ""
echo "After deployment, you'll have:"
echo "- Frontend: https://pizza-craft-web.onrender.com"
echo "- Admin: https://pizza-craft-admin.onrender.com"
echo "- API: https://pizza-craft-api.onrender.com"
echo ""
echo "Test login:"
echo "- Email: admin@pizzacraft.com"
echo "- Password: admin123"
